import Head from "next/head";
import Link from "next/link";

import { AuthButtons, ProductsList } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shopii</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto">
        <header className="flex items-center justify-between border-b-2 border-slate-600 p-5">
          <div>
            <Link href={"/admin"}>Admin Dashboard</Link>
          </div>

          <AuthButtons />
        </header>

        <ProductsList />
      </div>
    </>
  );
}
